---
- name: "set os-specific variables"
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: "install required os devel packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ rocksdb_os_devel_packages }}"
  become: yes
  environment: "{{ rocksdb_proxy_env }}"

- name: "clean up build directory"
  file:
    path: "{{ rocksdb_build_dir }}"
    state: absent
  when: rocksdb_build_dir_clean

- name: "prepare build and install directory"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rocksdb_build_dir }}"
    - "{{ rocksdb_src_dir }}"
    - "{{ rocksdb_install_dir }}"
    - "{{ rocksdb_install_dir }}/{{ rocksdb_binary_subdir }}"

- name: "download rocksdb source package"
  unarchive:
    src: "{{ rocksdb_sw_version_archive }}"
    dest: "{{ rocksdb_src_dir }}"
    creates: "{{ rocksdb_src_dir }}/Makefile"
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    validate_certs: no
  environment: "{{ rocksdb_proxy_env }}"

- name: "compile rocksdb software"
  make:
    chdir: "{{ rocksdb_src_dir }}"
    target: "{{ item }}"
    params:
      DEBUG_LEVEL: 0
  with_items: "{{ rocksdb_make_targets }}"

- name: "install rocksdb software"
  make:
    chdir: "{{ rocksdb_src_dir }}"
    target: install
