- name: "search for rocksdb tools"
  command: "find {{ rocksdb_src_dir }} {{ rocksdb_src_dir }}/tools -maxdepth 1 -type f -executable ! -iname 'librocksdb*'"
  register: "rocksdb_sw_tools"
  changed_when: "false"

- name: "install rocksdb tools"
  command: "install -C -v -m 755 {{ item }} {{ rocksdb_install_dir }}/{{ rocksdb_binary_subdir }}/{{ item|basename }}"
  with_items: "{{ rocksdb_sw_tools.stdout_lines }}"
  register: "installed"
  changed_when: installed.stdout != ""
  become: yes
